se/se/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView

from django.contrib import admin
admin.autodiscover()
import se.views
import video.views
import friendpair.views


urlpatterns = patterns("",
    #url(r"^$", TemplateView.as_view(template_name="homepage.html"), name="home"),
    url(r"^$",video.views.homepage_video_list, name="home"),
    url(r"^homepage$",se.views.personalPage),
    
    
    
    
    url(r"^admin/", include(admin.site.urls)),
    url(r"^account/signup/$", se.views.SignupView.as_view(), name="account_signup"),
    url(r"^account/settings/$", se.views.SettingsView.as_view(), name="account_settings"),
    url(r"^account/", include("account.urls")),
#    url(r"^ratings/", include("agon_ratings.urls")),

    url(r"^upload/$",video.views.upload),
    url(r"^upload/success/$",video.views.uploadSuccess),
    
    url(r"^videoplay/(\d+)$",video.views.video_play),

    url(r"^videoplay/(\d+)/ratings$",video.views.rate_video),
    url(r"^videoplay/(\d+)/comment$",video.views.comment_video),
    url(r"^videoModify/(\d+)$",video.views.video_modify),
    url(r"^videoDelete/(\d+)$",video.views.video_delete),
    url(r"^videoShare/(\d+)$",video.views.video_share),
        
    
    url(r"^personalPage/(\d+)$",se.views.personalPage, name="home"),
    
    url(r"^timeline$",se.views.timeline,name="timeLine"),
    url(r"^timeline/all$",se.views.timelineall,name="timeLine"),
    
    url(r"friend-manage",friendpair.views.friendManage, name="friend-manage")
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

se/video/models.py
from django.db import models
from django.contrib.auth.models import User


class Video(models.Model):
    owner = models.ForeignKey(User,related_name='video')
    uploadtime = models.DateTimeField(auto_now=True, auto_now_add=True)
    title = models.CharField(blank = True, max_length = 1000)
    description = models.CharField(blank = True, max_length = 1000)
    rating_sum = models.IntegerField(default=0)
    rating_person = models.IntegerField(default=0)
    file = models.FileField(upload_to='file/%Y/%m/%d', blank=True,null=True)


class Comment(models.Model):
    author = models.ForeignKey(User)
    video = models.ForeignKey(Video)
    content = models.TextField()
    time = models.DateTimeField(auto_now=True, auto_now_add=True)

se/se/forms.py
from django import forms
from django.forms.extras.widgets import SelectDateWidget

import account.forms


class SignupForm(account.forms.SignupForm):
    birthdate = forms.DateField(widget=SelectDateWidget(years=range(1910, 1991)))
    
class SettingsForm(account.forms.SettingsForm):
    birthdate = forms.DateField(widget=SelectDateWidget(years=range(1910, 1991)))    

se/se/views.py
import account.views
from django.shortcuts import render_to_response
from video.models import Video 
from django.template import RequestContext 
from django.contrib.auth.models import User
from friendpair.models import FriendPair
import se.forms


class SignupView(account.views.SignupView):
    form_class = se.forms.SignupForm

    def after_signup(self, form):
        self.create_profile(form)
        super(SignupView, self).after_signup(form)

    def create_profile(self, form):
        profile = self.created_user.get_profile()
        profile.birthdate = form.cleaned_data["birthdate"]
        profile.save()
       
class SettingsView(account.views.SettingsView):

    form_class = se.forms.SettingsForm
        
    def update_settings(self, form):
        self.update_info(form)
        super(SettingsView, self).update_settings(form)

    def update_info(self, form):
        if 'birthdate' in form.cleaned_data:
            profile = self.request.user.userprofile
            profile.birthday = form.cleaned_data['birthdate']
            profile.save()

    def get_initial(self):
        initial = super(SettingsView, self).get_initial()
        initial['birthdate'] = self.request.user.userprofile.birthday
        return initial
        

def personalPage(request,user_id = 0):

    
    if user_id == 0 or int(user_id) == request.user.id:
        page_owner = request.user
        flag = 0     # This is my own homepage
    else:
        page_owner = User.objects.get(id = int(user_id))
        if FriendPair.objects.filter(follower = request.user, master = page_owner).count() != 0:
            flag = 1 # already followed
        else:
            flag = 2 # have not yet followed


    videos = Video.objects.filter(owner=page_owner)

    if request.method == 'GET':
        pair = FriendPair()
        pair.follower = request.user
        pair.master = page_owner
        if FriendPair.objects.filter(follower = request.user, master = page_owner).count() == 0:
            pair.save()
    

    return render_to_response('personalPage.html', locals(),context_instance=RequestContext(request))



def timeline(request):
    user = request.user
    relationships = FriendPair.objects.filter(follower = user)
    masters = [pair.master for pair in relationships]
    videos = Video.objects.filter(owner__in=masters)
    videos = sorted(videos,key=lambda v:v.uploadtime,reverse=True)
    return render_to_response('timeLine.html', locals(),context_instance=RequestContext(request))

def timelineall(request):
    videos = Video.objects.all()
    return render_to_response('timeLine.html', locals(),context_instance=RequestContext(request))

se/se/templates/_account_bar.html
{% load i18n %}
{% load account_tags %}

<div class = "mybanner">
<ul>
<li><a href="/homepage" right-margin:20px>Home</a></li>
<li><a href="/timeline/all">Site Videos</a></li>
<li><a href="/timeline">Friend Videos</a></li>
<li><a href="/upload">Upload</a></li>
</div>


<ul class="nav navbar-nav pull-right">

    {% if request.user.is_authenticated %}
        <p class="navbar-text">
            <i class="fa fa-user"></i> {% user_display request.user %}
        </p>
        <li>
            <a href="{% url 'account_settings' %}"><i class="fa fa-cog"></i> {% trans "Settings" %}</a>
        </li>
        <li>
            <a id="account_logout" href="{% url 'account_logout' %}"><i class="fa fa-power-off"></i> {% trans "Log out" %}</a>
        </li>
    {% else %}
        <li><a href="{% url 'account_login' %}">{% trans "Log in" %}</a></li>
        {% if ACCOUNT_OPEN_SIGNUP %}
            <li><a href="{% url 'account_signup' %}">{% trans "Sign up" %}</a></li>
        {% endif %}
    {% endif %}
</ul>

<form id="accountLogOutForm" style="display: none;" action="{% url 'account_logout' %}" method="POST">
    {% csrf_token %}
</form>

se/se/templates/_footer.html
{% load i18n %}

{% trans "&copy; 2014 &lt;FDU copyright reserved&gt;" %}

se/se/templates/banner_base.html
{% extends "site_base.html" %}

{% load i18n %}

{% block body %}
    <div class="jumbotron">
     
    {% block banner %}
        <h1>Hello, world!</h1>
        <p>Vestibulum id ligula porta felis euismod semper. Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit.</p>
        <p><a class="btn btn-primary btn-large">Learn more &raquo;</a></p>
    {% endblock %}
    </div>
    

{% endblock %}

se/se/templates/friendManage.html
{% extends "banner_base.html" %}

{% block banner %}

This is the friend manage page.

{% endblock %}

se/se/templates/homepage.html
{% extends "banner_base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Welcome" %}{% endblock %}

{% block body_class %}home{% endblock %}

{% block banner %}

    <h1>Welcome to VideoShare.com!</h1>

    <h2>Latest Uploaded Videos</h2>
    <p>



    <table>
    <tr>
    {% for video in highscore %}
        <td>
            <table>
            <tr>
            <td>
            <video width="160" height="120"  controls>
              <source src="{{video.file.url}}" type="video/mp4">
            </video>
            </td>
            </tr>
            <tr><td><b>uploader：</b>{{video.owner.username}}</td></tr>
            <tr><td><b>description：</b>{{video.description}}</td></tr>
            </table>
        </td>
    {% endfor %}
    </tr>
    </table>



    </p>

    <h2>Highest Rated Videos</h2>
    <p>

    <table>
    <tr>
    {% for video in latest %}
        <td>
            <table>
            <tr>
            <td>
            <video width="160" height="120"  controls>
              <source src="{{video.file.url}}" type="video/mp4">
            </video>
            </td>
            </tr>
            <tr><td><b>uploader：</b>{{video.owner.username}}</td></tr>
            <tr><td><b>description：</b>{{video.description}}</td></tr>
            </table>
        </td>
    {% endfor %}
    </tr>
    </table>

    </p>


{% endblock %}

se/se/templates/personalPage.html
{% extends "banner_base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Welcome" %}{% endblock %}

{% block body_class %}home{% endblock %}

{% block banner %}

<a href="/timeline/all" class="btn btn-default">All Videos</a>
<a href="/timeline" class="btn btn-default">Videos from friends</a>
</br>
	<p>
	username: {{page_owner.username}}, uid: {{page_owner.id}}
	{% if flag ==  2 %} 
	<form action = '' method = 'get'>
		<input type = 'submit' value = 'Follow' />
	</form>
	{% elif flag == 1 %}
		followed
	{% endif %}
	</p>
	<h3>My videos</h3>
	<table class="table">
	    <th>Title</th>
	    <th>User</th>
	    <th>Time</th>
		{% for video in videos %}
		<tr>
		    <td><a href="/videoplay/{{video.id}}">{{video.title}}</a></td>
			<td><a href="/personalPage/{{video.owner.id}}">{{video.owner.username}}</a></td>
			<td>{{video.uploadtime}}</td>
		</tr>
		{% endfor %}
	</table>
{% endblock %}

se/se/templates/site_base.html
{% extends "theme_bootstrap/base.html" %}

{% load staticfiles %}
{% load metron_tags %}
{% load i18n %}


{% block style_base %}
    <link href="{% static "pinax/css/theme.css" %}" rel="stylesheet">
    <link href="{% static "css/site.css" %}" rel="stylesheet">
    {% block extra_style %}
    <link href="{% static "css/my.css" %}" rel="stylesheet">
    {% endblock %}
{% endblock %}


{% block extra_head_base %}
    {% block extra_head %}{% endblock %}
{% endblock %}


{% block footer %}
    {% include "_footer.html" %}
{% endblock %}


{% block extra_body_base %}
    {% analytics %}
    {% block extra_body %}{% endblock %}
{% endblock %}


{% block script_base %}
    <script src="{% block jquery_src %}{% static "jquery/js/jquery-2.1.1.min.js" %}{% endblock %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <script src="{% static "pinax/js/theme.js" %}"></script>


{% block extra_script %}
<script src="{% static "js/video_rating.js" %}"></script>
{% endblock %}
{% endblock %}

se/se/templates/timeLine.html
{% extends "banner_base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Welcome" %}{% endblock %}

{% block body_class %}home{% endblock %}

{% block banner %}

<a href="/homepage" class="btn btn-default">My Homepage</a>
<a href="/timeline/all" class="btn btn-default">All Videos</a>
<a href="/timeline" class="btn btn-default">Videos from friends</a>
<br />
<br />

<table class="table">
    <tr>
        <th>Title</th>
        <th>User</th>
        <th>Time</th>
    </tr>
    
{% for video in videos %}

    <tr>
	    <td><a href="/videoplay/{{video.id}}">{{video.title}}</a></td>
	    <td><a href="/personalPage/{{video.owner.id}}">{{video.owner.username}}</a> </td>
	    <td>{{video.uploadtime}}</td>
	</tr>
{% endfor %}
</table>

{% endblock %}

se/se/templates/upload.html
{% extends "banner_base.html" %}

{% block banner %}
    <a>视频文件{% if uploadFlag %}上传{% else %}修改{% endif %}</a>
     <form enctype="multipart/form-data" method="post" action="">
        {% csrf_token %}
        <table>
        <tr>
            <th><label for="id_title">title:</label></th>
            <td><input id="id_title" maxlength="100" name="title" type="text" value="{{video_object.title}}" /></td>
            </tr>
        <tr>
            <th><label for="id_description">description:</label></th>
            <td><input id="id_description" maxlength="1000" name="description" type="text" value="{{video_object.description}}"/></td>
        </tr>
        
        {% if uploadFlag %}
            <tr>
                <th><label for="id_file">File:</label></th>
                <td><input id="id_file" name="file" type="file" /></td>
            </tr>
        {% endif %}
        </table>
        
        <input id="submit" type="submit" value="submit" />
      </form>
{% endblock %}

se/se/templates/upload_Success.html
{% extends "banner_base.html" %}

{% block banner %}
    <h2>Upload succeeded.</h2>
{% endblock %}

se/se/templates/videoplay.html
{% extends "banner_base.html" %}

{% load i18n %}

{% block head_title %}{% trans "Welcome" %}{% endblock %}

{% block body_class %}home{% endblock %}

{% block banner %}

<h2>{{video_object.title}}</h2><br/>

<video width="640" height="480"  controls>
<source src="{{video_path}}" type="video/mp4">
</video>
<!-- JiaThis Button BEGIN -->

<div class="jiathis_style">
	<a class="jiathis_button_qzone"></a>
	<a class="jiathis_button_tsina"></a>
	<a class="jiathis_button_tqq"></a>
	<a class="jiathis_button_weixin"></a>
	<a class="jiathis_button_renren"></a>
	<a href="http://www.jiathis.com/share" class="jiathis jiathis_txt jtico jtico_jiathis" target="_blank"></a>
	<a class="jiathis_counter_style"></a>
</div>
<script type="text/javascript" src="http://v3.jiathis.com/code/jia.js" charset="utf-8"></script>
<!-- JiaThis Button END -->
<br/>
<table class="table">
<tr class='active'>
<th>上传者</th>
<th>视频描述</th>
<th>评级</th>
</tr>
<tr>
    <td>{{video_object.owner.username}}</td>
    <td>{{video_object.description}}</td>
    <td><span id = "ratings">{{points}} </span></p></td>

</tr>
</table>

</p>


<p>
{% if own %} 
    <a href="/videoModify/{{video_object.id}}" class="btn btn-default">Edit</a> 
    <a href="/videoDelete/{{video_object.id}}" class="btn btn-default">Delete</a> <br/>
{% else %}
    <a href="/videoShare/{{video_object.id}}" class="btn btn-default">Share To Timeline</a>
{% endif %} 
</p>

<br/>
    <form id = "RatingForm" method="post" action="/videoplay/{{video_object.id}}/ratings">
        <a>Rating</a><br/>

        {% csrf_token %}
        评级：
        <input type="radio" name="rate" value="1" /> 1
        <input type="radio" name="rate" value="2" /> 2
        <input type="radio" name="rate" value="3" /> 3
        <input type="radio" name="rate" value="4" /> 4
        <input type="radio" name="rate" value="5" /> 5

        <input name ="ratingsubmit" id="ratingsubmit" type="submit" value="评分" />
    </form>



<br/>


<a>提交评论</a>
<form id = "CommentForm" method="post" action="/videoplay/{{video_object.id}}/comment">
    {% csrf_token %}
    <textarea id="id_title" maxlength="1000"   name="content" type="text"> </textarea>
    <input name ="commentsubmit" id="commentsubmit" type="submit" value="评论" />
</form>




<div id = "Comment">
<table class = table>

{% for comment in commentList %}
<tr class="active">
    <td>{{comment.author.username}}</td>
    <td>{{comment.time}}</td>
</tr>
<tr>
   <td> {{comment.content}}</td>
</tr>
{% endfor %}

</table>
</div>

{% endblock %}